server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: timetracker-backend
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:timetracker}
    username: ${DB_USERNAME:timetracker}
    password: ${DB_PASSWORD:timetracker}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:idp.localhost}/realms/${KEYCLOAK_REALM:tt-realm}
          jwk-set-uri: http://${KEYCLOAK_HOST:idp.localhost}/realms/${KEYCLOAK_REALM:tt-realm}/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://${KEYCLOAK_HOST:idp.localhost}
  realm: ${KEYCLOAK_REALM:tt-realm}
  resource: ${KEYCLOAK_CLIENT_ID:PEAX-agent}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:b1c84ea2-32f2-4229-a1c1-09e5c29363b6}
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    com.company.timetracker: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Custom application properties
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:3000}
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  
  vacation:
    auto-approval-roles: ADMIN,HR_MANAGER
    max-days-per-request: 30
    advance-notice-days: 7

---
spring:
  config:
    activate:
      on-profile: development
  
  datasource:
    url: jdbc:postgresql://localhost:5432/timetracker_dev
    username: timetracker_dev
    password: timetracker_dev
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: INFO
    com.company.timetracker: DEBUG

---
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  
  flyway:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: production
  
  jpa:
    show-sql: false
  
logging:
  level:
    root: WARN
    com.company.timetracker: INFO
